import Logo from '../assets/images/logo/logo-dark.png';

export const tasksData = [
  {
    bankName: 'Axis Bank',
    taskName: 'task one',
    businessType: 'Jwelry shop',
    assignee: 'status',
    status: 'status',
    reporter: 'reporter',
    action: 'action',
  },
];

export const tasksTableColumn = [
  {
    bankIcon: Logo,
    bankName: 'Axis Bank',
    taskName: 'PD Loan 1',
    businessType: 'Jewellary Shop',
    status: 'inProgress',
    assignee: 'Prabhat',
    reporter: 'Seemit',
    action: '06/2026',
  },
  {
    bankIcon: Logo,
    bankName: 'Axis Bank',
    taskName: 'PD Loan 2',
    businessType: 'Jewellary Shop',
    status: 'completed',
    assignee: 'Abhishek',
    reporter: 'Seemit',
    action: '06/2026',
  },
  {
    bankIcon: Logo,
    bankName: 'Axis Bank',
    taskName: 'PD Loan 3',
    businessType: 'Jewellary Shop',
    status: 'open',
    assignee: 'Abhishek',
    reporter: 'Seemit',
    action: '06/2026',
  },
  {
    bankIcon: Logo,
    bankName: 'Axis Bank',
    taskName: 'PD Loan 4',
    businessType: 'Jewellary Shop',
    status: 'inProgress',
    assignee: 'Shweta',
    reporter: 'Seemit',
    action: '06/2026',
  },
  {
    bankIcon: Logo,
    bankName: 'Axis Bank',
    taskName: 'PD Loan 5',
    businessType: 'Jewellary Shop',
    status: 'open',
    assignee: 'Palash',
    reporter: 'Seemit',
    action: '06/2026',
  },
  {
    bankIcon: Logo,
    bankName: 'Axis Bank',
    taskName: 'PD Loan 6',
    businessType: 'Jewellary Shop',
    status: 'completed',
    assignee: 'Roshan',
    reporter: 'Seemit',
    action: '06/2026',
  },
];

export const usersTableColumn = [
  {
    img: Logo,
    name: 'John Michael',
    email: 'john@creative-tim.com',
    contact: '+91 7047026537',
    role: 'Supervisor',
    reportCount: 20,
    joined: '23/04/18',
  },
  {
    img: Logo,
    name: 'Alexa Liras',
    email: 'alexa@creative-tim.com',
    contact: '+91 7047026537',
    role: 'Reporter',
    reportCount: 30,
    joined: '23/04/18',
  },
  {
    img: Logo,
    name: 'Laurent Perrier',
    email: 'laurent@creative-tim.com',
    contact: '+91 7047026537',
    role: 'Supervisor',
    reportCount: 11,
    joined: '19/09/17',
  },
  {
    img: Logo,
    name: 'Michael Levi',
    email: 'michael@creative-tim.com',
    contact: '+91 7047026537',
    role: 'Reporter',
    reportCount: 24,
    joined: '24/12/08',
  },
  {
    img: Logo,
    name: 'Richard Gran',
    email: 'richard@creative-tim.com',
    contact: '+91 7047026537',
    role: 'Reporter',
    reportCount: 21,
    joined: '04/10/21',
  },
];

export const reportsTableColumn = [
  {
    img: Logo,
    name: 'Axis Bank',
    amount: 'PD Loan 1',
    joined: 'Jewellary Shop',
    status: 'open',
    account: 'visa',
    accountNumber: 'Seemit',
    expiry: '06/2026',
  },
  {
    img: Logo,
    name: 'Amazon',
    amount: '$5,000',
    joined: 'Wed 1:00pm',
    status: 'open',
    account: 'master-card',
    accountNumber: 'Seemit',
    expiry: '06/2026',
  },
  {
    img: Logo,
    name: 'Pinterest',
    amount: '$3,400',
    joined: 'Mon 7:40pm',
    status: 'pending',
    account: 'master-card',
    accountNumber: 'Seemit',
    expiry: '06/2026',
  },
  {
    img: Logo,
    name: 'Google',
    amount: '$1,000',
    joined: 'Wed 5:00pm',
    status: 'open',
    account: 'visa',
    accountNumber: 'Seemit',
    expiry: '06/2026',
  },
  {
    img: Logo,
    name: 'netflix',
    amount: '$14,000',
    joined: 'Wed 3:30am',
    status: 'cancelled',
    account: 'visa',
    accountNumber: 'Seemit',
    expiry: '06/2026',
  },
];

