import Logo from '../assets/images/logo/logo-dark.png';

export const tasksData = [
  {
    bankName: 'Axis Bank',
    taskName: 'task one',
    businessType: 'Jwelry shop',
    assignee: 'assignee',
    status: 'status',
    reporter: 'reporter',
    action: 'action',
  },
];

export const tasksTableColumn = [
  {
    bankIcon: Logo,
    bankName: 'Spotify',
    taskName: '$2,500',
    businessType: 'Wed 3:00pm',
    assignee: 'paid',
    status: 'visa',
    reporter: '1234',
    action: '06/2026',
  },
  {
    bankIcon: Logo,
    bankName: 'Spotify',
    taskName: '$2,500',
    businessType: 'Wed 3:00pm',
    assignee: 'paid',
    status: 'visa',
    reporter: '1234',
    action: '06/2026',
  },
  {
    bankIcon: Logo,
    bankName: 'Spotify',
    taskName: '$2,500',
    businessType: 'Wed 3:00pm',
    assignee: 'paid',
    status: 'visa',
    reporter: '1234',
    action: '06/2026',
  },
  {
    bankIcon: Logo,
    bankName: 'Spotify',
    taskName: '$2,500',
    businessType: 'Wed 3:00pm',
    assignee: 'paid',
    status: 'visa',
    reporter: '1234',
    action: '06/2026',
  },
  {
    bankIcon: Logo,
    bankName: 'Spotify',
    taskName: '$2,500',
    businessType: 'Wed 3:00pm',
    assignee: 'paid',
    status: 'visa',
    reporter: '1234',
    action: '06/2026',
  },
  {
    bankIcon: Logo,
    bankName: 'Spotify',
    taskName: '$2,500',
    businessType: 'Wed 3:00pm',
    assignee: 'paid',
    status: 'visa',
    reporter: '1234',
    action: '06/2026',
  },
];

export const usersTableColumn = [
  {
    img: Logo,
    name: 'John Michael',
    email: 'john@creative-tim.com',
    job: 'Manager',
    org: 'Organization',
    online: true,
    date: '23/04/18',
  },
  {
    img: Logo,
    name: 'Alexa Liras',
    email: 'alexa@creative-tim.com',
    job: 'Programator',
    org: 'Developer',
    online: false,
    date: '23/04/18',
  },
  {
    img: Logo,
    name: 'Laurent Perrier',
    email: 'laurent@creative-tim.com',
    job: 'Executive',
    org: 'Projects',
    online: false,
    date: '19/09/17',
  },
  {
    img: Logo,
    name: 'Michael Levi',
    email: 'michael@creative-tim.com',
    job: 'Programator',
    org: 'Developer',
    online: true,
    date: '24/12/08',
  },
  {
    img: Logo,
    name: 'Richard Gran',
    email: 'richard@creative-tim.com',
    job: 'Manager',
    org: 'Executive',
    online: false,
    date: '04/10/21',
  },
];

export const reportsTableColumn = [
  {
    img: Logo,
    name: 'Spotify',
    amount: '$2,500',
    date: 'Wed 3:00pm',
    status: 'paid',
    account: 'visa',
    accountNumber: '1234',
    expiry: '06/2026',
  },
  {
    img: Logo,
    name: 'Amazon',
    amount: '$5,000',
    date: 'Wed 1:00pm',
    status: 'paid',
    account: 'master-card',
    accountNumber: '1234',
    expiry: '06/2026',
  },
  {
    img: Logo,
    name: 'Pinterest',
    amount: '$3,400',
    date: 'Mon 7:40pm',
    status: 'pending',
    account: 'master-card',
    accountNumber: '1234',
    expiry: '06/2026',
  },
  {
    img: Logo,
    name: 'Google',
    amount: '$1,000',
    date: 'Wed 5:00pm',
    status: 'paid',
    account: 'visa',
    accountNumber: '1234',
    expiry: '06/2026',
  },
  {
    img: Logo,
    name: 'netflix',
    amount: '$14,000',
    date: 'Wed 3:30am',
    status: 'cancelled',
    account: 'visa',
    accountNumber: '1234',
    expiry: '06/2026',
  },
];

