export const reportData: any = {};

export const initailReportPayload = {
  caseId: '656380f829a29b03abbaa394',
  data: {
    loanDetails: {
      alc: '',
      loan: '',
      loanType: '',
      bankName: '',
    },
    pdDetails: {
      location: '',
      reporterName: '',
      reporterContact: '',
      pdVisitDate: '',
      pdConductTime: '',
      reviewerName: '',
      reviewerContact: '',
      reportTat: '',
      reportSentDate: '',
    },
    personalDetails: {
      applicants: [
        {
          title: 'Applicant Info',
          name: '',
          dobDoi: '',
          qualification: '',
          natureOfBusiness: '',
          birthYear: '',
          age: '',
          studyFinish: '',
          study: '',
          businessStart: '',
          currExp: '',
          pastExp: '',
          overallExp: '',
        },
        {
          title: 'Applicant Info',
          name: '',
          dobDoi: '',
          qualification: '',
          natureOfBusiness: '',
          birthYear: '',
          age: '',
          studyFinish: '',
          study: '',
          businessStart: '',
          currExp: '',
          pastExp: '',
          overallExp: '',
        },
      ],
      residents: [
        {
          title: 'Residance Info',
          resiAddress: '',
          resiStatus: '',
          resiType: '',
          resiSince: '',
          buildArea: '',
          carpetArea: '',
          purchaseYear: '',
          agrimentValue: '',
          purchaseValue: '',
          marketValue: '',
          rentPm: '',
        },
        {
          title: 'Residance Info',
          resiAddress: '',
          resiStatus: '',
          resiType: '',
          resiSince: '',
          buildArea: '',
          carpetArea: '',
          purchaseYear: '',
          agrimentValue: '',
          purchaseValue: '',
          marketValue: '',
          rentPm: '',
        },
      ],
      familyDetails: [
        {
          name: '',
          relation: '',
          earningStatus: '',
        },
        {
          name: '',
          relation: '',
          earningStatus: '',
        },
      ],
    },
    existingLoan: {
      existanceLoan: {
        isExistanceLoan: 'Yes',
        balanceTransfer: [
          {
            title: '',
            typeOfLoan: '',
            bankName: '',
            loanAmount: '',
            tenureMonth: '',
            emi: '',
            outstanding: '',
            remark: '',
          },
        ],
        totalLoanBt: 0,
        totalLoanBtEmi: 0,
        totalLoanBtOut: 0,
        existingLoanClosed: [
          {
            title: '',
            typeOfLoan: '',
            bankName: '',
            loanAmount: '',
            tenureMonth: '',
            emi: '',
            outstanding: '',
            remark: '',
          },
        ],
        totalLoanEc: 0,
        totalLoanEcEmi: 0,
        totalLoanEcOut: 0,
        existingLoanEMI: [
          {
            title: '',
            typeOfLoan: '',
            bankName: '',
            loanAmount: '',
            tenureMonth: '',
            emi: '',
            outstanding: '',
            remark: '',
          },
        ],
        totalLoanEm: 0,
        totalLoanEmEmi: 0,
        totalLoanEmOut: 0,
      },
      creditFacility: {
        isCreditFacility: 'Yes',
        creditDetails: [
          {
            title: 'Credit Facility',
            typeOfFacility: '',
            bankName: '',
            limit: '',
            averageUtilization: '',
            interestRate: '',
            remark: '',
          },
        ],
        totalLoanCfLimit: 0,
        totalLoanCfAu: 0,
      },
      otherCommitments: {
        isOtherCommitmemts: 'Yes',
        commitmentsDetails: [
          {
            title: 'Other Commitment',
            particulars: '',
            contribution: '',
            sumAssured: '',
          },
          {
            title: 'Other Commitment',
            particulars: '',
            contribution: '',
            sumAssured: '',
          },
        ],
        totalCon: 0,
        totalSum: 0,
      },
    },
    detailsOfProp: {
      purchaseYear: '',
      buildUpArea: '',
      caretArea: '',
      occupiedBy: '',
      loanPropertyAddress: '',
      builderName: '',
      propertyLoanDetails: {
        isLoanProvided: '',
        loanDetails: { amount: '', emi: '', roi: '', year: '' },
        propertyValue: {
          agreementValue: 0,
          purchaseValue: 0,
          marketValue: 0,
          ocrPaid: 0,
          pOrb: '',
          balanceOcr: 0,
          sourceOcr: '',
        },
        loanAsPerForm: '',
      },
    },
    businessDetails: {
      bussinessName: '',
      typeOfEntity: '',
      yearOfIncorporation: '',
      generation: '',
      gstNumber: '',
      regOfficeAddress: '',
      visitedAddress: '',
      vicinity: '',
      ownership: '',
      pdConductWith: '',
      designation: '',
      mobile: '',
      familyBusiness: '',
      mainUseproducts: '',
      howTurnoverVerified: '',
      citiesOfReppresentation: '',
      competitorsOfBusiness: '',
      noOfVisit: 1,
      doYouHavefixedEmployee: '',
      empSpecified: 0,
      empSeen: 0,
      shareHoldings: [
        {
          ownerName: '',
          shareHolding: 0,
        },
      ],
      totalHolding: 0,
    },
    financials: {
      totalEarning: 363,
      finances: [
        {
          title: 'Financial Details',
          entityName: '',
          applicantIncome: '',
          income: {
            turnoverGrossReciepts: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            purchases: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            grossProfit: 0,
            grossProfitPer: 0,
          },
          expenses: {
            salary: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            maintanance: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            transport: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            electricity: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            travelling: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            fuel: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            officeRent: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            partnersSalary: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            partnersRemuneration: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            otherExpenses: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            bifercationOfExpenses: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            totalExpensePA: '',
            totalExpensePM: '',
            netProfitPA: '',
            netProfitPM: '',
            shareOfProfitPA: '',
            shareOfProfitPM: '',
          },
          businessIncome: {
            salaryFromBusiness: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            remunerationFromBusiness: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            rent: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            totalIncomePA: '',
            totalEarning: '',
          },
        },
        {
          title: 'Financial Details',
          entityName: '',
          applicantIncome: '',
          income: {
            turnoverGrossReciepts: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            purchases: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            grossProfit: 0,
            grossProfitPer: 0,
          },
          expenses: {
            salary: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            maintanance: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            transport: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            electricity: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            travelling: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            fuel: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            officeRent: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            partnersSalary: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            partnersRemuneration: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            otherExpenses: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            bifercationOfExpenses: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            totalExpensePA: '',
            totalExpensePM: '',
            netProfitPA: '',
            netProfitPM: '',
            shareOfProfitPA: '',
            shareOfProfitPM: '',
          },
          businessIncome: {
            salaryFromBusiness: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            remunerationFromBusiness: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            rent: {
              amountPA: '',
              amountPM: '',
              months: 12,
            },
            totalIncomePA: '',
            totalEarning: '',
          },
        },
      ],
    },
    comitmentSummary: {
      proposedEMI: { amountPA: 0, amountPM: 0 },
      existingEMI: { amountPA: 0, amountPM: 0 },
      btEMI: { amountPA: 0, amountPM: 0 },
      closureEMI: { amountPA: 0, amountPM: 0 },
      licMedSipTpOther: { amountPA: 0, amountPM: 0 },
      houseRent: { amountPA: 0, amountPM: 0 },
      totalCommitments: { amountPA: 0, amountPM: 0 },
      totalPresentEMI: { amountPA: 0, amountPM: 0 },
      existingCommitments: { amountPA: 0, amountPM: 0 },
      onlyEMIRatio: '',
      foirRatio: '',
      totalCommitmentsRatio: '',
    },
    turnoverDetails: {
      aprilTillDate: {
        idealAprilTillDate: {
          turnover: 0,
          netProfit: 0,
        },
        aprilTillDate: {
          turnover: 0,
          netProfit: 0,
        },
        reasonforDiff: '',
      },
      lastYears: {
        firstLastYear: 0,
        secondLastYear: 0,
        changes: '',
        reasonforDiff: '',
      },
      currentYearActual: {
        actuals: {
          turnover: 0,
          netProfit: 0,
          profitPercentage: 0,
        },
        asPerFinancials: {
          turnover: 0,
          netProfit: 0,
          profitPercentage: 0,
        },
        financialActualRatio: '',
      },
      currentLastYearComparision: {
        firstLastYear: 0,
        secondLastYear: 0,
        changes: '',
        reasonforDiff: '',
      },
      bussinessTrendLast2Year: '',
      futureProjection: '',
    },
    clientDebtors: {
      clients: {
        isClientDetails: '',
        clientDetails: {
          noOfClientDaily: '',
          majorClient: [{ clientName: '', contact: '' }],
        },
      },
      debitors: {
        isDebitorDetails: '',
        debitorDetails: {
          moreThan6Month: {
            amount: 0,
            reason: '',
          },
          lessThan6Month: {
            amount: 0,
          },
          totalDebtors: 0,
          collectionPeriod: '',
          creditPeriodAllowed: '',
          whyIrRegular: '',
        },
      },
    },
    stocks: {
      isStockDetails: 'Yes',
      stockDetails: {
        rawMaterialAmount: 0,
        wipAmount: 0,
        finishGoods: 0,
        whyStocklowHigh: 0,
        totalStocks: 0,
        stockHoldingPeriod: '',
      },
    },
    suppliers: {
      isSuppliersDetails: 'Yes',
      suppliersDetails: {
        noOfSuppliers: '',
        majorSuppliers: [{ clientName: '', contact: '' }] as any,
      },
      creditors: {
        amount: 0,
      },
      collectionPeriod: '',
      creitPeriodAllowed: '',
      whyCreditorHighThanCredit: '',
    },
    assets: {
      isBussinessAssets: '',
      bussinessAssetDetails: {
        bussinessAssets: [
          {
            title: 'Asset',
            particulars: '',
            location: '',
            purchaseYear: '',
            carpetArea: '',
            status: '',
            marketValue: '',
            rentPM: '',
          },
        ],
        totalMarketValue: '',
        totalRentPM: '',
      },
      isPersonalAssets: '',
      personalAssetDetails: {
        personalAssets: [
          {
            title: 'Asset',
            particulars: '',
            location: '',
            purchaseYear: '',
            carpetArea: '',
            status: '',
            marketValue: '',
            rentPM: '',
          },
        ],
        totalMarketValue: '',
        totalRentPM: '',
      },
      isInvestments: '',
      investmentDetails: {
        investments: [
          {
            title: 'Investment',
            particulars: '',
            contribution: '',
            marketValue: '',
          },
        ],
        totalContribution: '',
        totalMarketValue: '',
      },
      isBankAccount: '',
      bankAccountDetails: {
        bankAccounts: [
          {
            title: 'Bank Account',
            bankName: '',
            branch: '',
            type: '',
            balanceOnDay: '',
          },
        ],
        totalBalance: '',
      },
      assetsBacking: '',
    },
    observations: {
      businessPlateName: {
        exist: '',
        reasonForNo: '-',
      },
      activity: {
        exist: '',
        reasonForNo: '-',
      },
      customer: {
        exist: '',
        reasonForNo: '',
      },
      stock: {
        exist: '',
        reasonForNo: '-',
      },
      thirdPartyCheck: {
        exist: '',
        reasonForNo: '',
      },
      screenshotOfCCTV: {
        exist: '',
        reasonForNo: '-',
      },
      behaviourOfApplicant: '',
      duringVist: {
        applicantDoing: '',
        employeesDoing: '',
        otherObservation: '',
      },
    },
    documentsSeen: [
      {
        label: 'Documents were not handy during PD.',
        isDoc: 'No',
      },
      {
        label:
          'No documents provided & applicant said Documents are already given to bank.',
        isDoc: 'No',
      },
      { label: 'GST Returns', isDoc: 'No' },
      {
        label: 'GST Registration Certificate',
        isDoc: 'No',
      },
      {
        label: 'Financial Statements of March Current Year',
        isDoc: 'No',
      },
      {
        label: 'Financial Statements of March Last Year',
        isDoc: 'No',
      },
      {
        label: 'Financial Statements of March Second Last Year',
        isDoc: 'No',
      },
      { label: 'Sales Bills', isDoc: 'No' },
      { label: 'Purchase Bills', isDoc: 'No' },
      { label: 'ITR for March Current Year', isDoc: 'No' },
      { label: 'ITR for March Last Year', isDoc: 'No' },
      {
        label: 'ITR for March Second Last Year',
        isDoc: 'No',
      },
      { label: 'Udyam Aadhar', isDoc: 'No' },
      {
        label: 'Vehicle Registration (RC Book)',
        isDoc: 'No',
      },
      { label: 'Gumasta', isDoc: 'No' },
      { label: 'RC Book', isDoc: 'No' },
      { label: 'Salary Slip', isDoc: 'No' },
      {
        label: 'Provisional Financials for March Last Year',
        isDoc: 'No',
      },
      { label: 'Financials in Tally', isDoc: 'No' },
    ],
    businessOf: { bussinessProcessOf: 'salaried' },
  },
};
